### ISSUE TITLE
navbar.php doesn't work

### ISSUE THREAD

**Issue by coliff** [Rundiz/bootstrap4-basic-template#2]
There are errors in the PHP version of the Navbar page. It doesn't load in a browser.

**Comment by ve3** [comment]
Hello :)

What is the error message?

Do you run it in /_php-doc? If yes, that is not gonna work because it must be copy to upper directory (same as README.md file location).

What version of PHP are you using? It required at least PHP 5.4.

**Comment by coliff** [comment]
Error:Parse error: syntax error, unexpected '[' on the line with:  $color_schemes = [

**Comment by ve3** [comment]
You are using PHP older than 5.4. (http://stackoverflow.com/questions/11912233/php-array-syntax-parse-error-left-square-bracket)
Please update to PHP 5.4 or newer. However even PHP 5.4 is too old for me but that's ok. :)

**Comment by coliff** [comment]
thanks for the info. I updated PHP on my server and all good now. :-)
