### ISSUE TITLE
Move HTML files to gh-pages

### ISSUE THREAD

**Issue by coliff** [Rundiz/bootstrap4-basic-template#3]
If we move the HTML/JS/CSS to gh-pages then users would be able to browse this project in a browser without needing to first download it. Would be easy to do - what do you think?

**Comment by ve3** [comment]
[Yabadabadoo](https://rundiz.github.io/bootstrap4-basic-template/)...


No need to duplicate to gh-pages, there is an option to use master branch as GitHub page.
